const GET_USERS = 'GET_USERS',
    GET_SINGLE_USER = 'GET_SINGLE_USER',
    CREATE_USER = 'CREATE_USER',
    UPDATE_USER = 'UPDATE_USER',
    DELETE_USER = 'DELETE_USER',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_LOADING = 'USER_LOADING';

export { GET_USERS, GET_SINGLE_USER, CREATE_USER, UPDATE_USER, DELETE_USER, USER_NOT_FOUND, USER_LOADING }